### ISSUE TITLE
Interval doesn't work correctly

### ISSUE THREAD

**Issue by aj3423** [jasonlvhit/gocron#72] opened 2019-06-22 17:08 UTC
I try to run a task every **3** seconds, but it still runs **every** second:

	func Hello() {
		fmt.Printf("hello %d\n", time.Now().Unix())
	}

	func main() {
		gocron.Every(3).Seconds().Do(Hello)
		<-gocron.Start()
	}

The result is:

	hello 1561223112
	hello 1561223113
	hello 1561223114
	hello 1561223115
	hello 1561223116
	hello 1561223117
	hello 1561223118

**Comment by lilpp** [comment] 2019-06-27 12:50
Same problem here, but it is working with older 5bcdd9fcfa9b commit.

**Comment by bstock92** [comment] 2019-07-05 12:48
Yes, the current master branch is broken for my use case and 5bcdd9f seems to work more closely to the desired behaviour.

**Comment by jaisonz** [comment] 2019-07-17 06:33
The interval is always one second whatever the interval value you add.

**Comment by Streppel** [comment] 2019-07-17 10:27
That's odd. Running on the main branch the behavior I get when trying @aj3423 example's is what I expected:

```
hello 1563359106
hello 1563359109
hello 1563359112
hello 1563359115
hello 1563359118
hello 1563359121
hello 1563359124
hello 1563359127
```

Maybe this last commit fixed it?

**Comment by Streppel** [comment] 2019-07-17 10:46
The fix has been merged.

**Comment by aj3423** [comment] 2019-07-17 14:55
@Streppel I tried update the library and run the code again, the problem still exists, it still delays 1 second instead of 3 seconds.

**Comment by Streppel** [comment] 2019-07-17 16:29
@aj3423 oh, we may be missing something. Did you ran the main branch? I cannot reproduce this now after the merge
![Peek 2019-07-17 13-27](https://user-images.githubusercontent.com/2300328/61393208-da261380-a896-11e9-9750-462ed072dd0e.gif)

**Comment by aj3423** [comment] 2019-07-17 16:42
@Streppel Yes I tried with the master branch. I can see the commit from git history.  My environment is:  go version go1.11.5 windows/amd64
![image](https://user-images.githubusercontent.com/4710875/61393984-be515a80-a8f4-11e9-99e2-b256197352a8.png)

**Comment by Streppel** [comment] 2019-07-17 16:56
@aj3423 thank you for the details. I'll try to investigate any further and try to reproduce the problem. Any thoughts on this, anyone?

**Closed** 2019-07-19 17:20 UTC
Labels: 3 - Review, bug

**Comment by Streppel** [comment] 2019-07-19 17:23
@aj3423 a new fix has been merged! There was indeed a problem. Please, update your dependencies and let me know what you think! In case of still running into issues and we'll reopen this issue :)

**Comment by aj3423** [comment] 2019-07-19 17:23
@Streppel I just tried again, now it works fine. Thanks.

**Comment by Streppel** [comment] 2019-07-19 17:29
@aj3423 awesome! Thank you for bringing it up. :)
