### ISSUE TITLE
DoSafely() doesn't actually do anything

### ISSUE THREAD

**Issue by JohnRoesler** [jasonlvhit/gocron#117] opened 2019-10-28 19:12 UTC
When running a task with `DoSafely`, it never actually performs the task.

Here is an example main.go file:

```
package main

import (
	"io/ioutil"
	"log"

	"github.com/jasonlvhit/gocron"
)

func task() {
	log.Println("I am runnning task.")
	d1 := []byte("hello\ngo\n")
	ioutil.WriteFile("/tmp/dat1", d1, 0644)
}

func main() {
	s := gocron.NewScheduler()
	s.Every(3).Seconds().DoSafely(task)
	<-s.Start()
}
```

Test it out - if you swap in `Do` for `DoSafely` it works as expected, outputs to the terminal and writes the file. With `DoSafely` nothing happens.

**Comment by Streppel** [comment] 2019-10-28 19:27
@preslavrachev would you have the time to take a look into it? if not please let me know

**Comment by preslavrachev** [comment] 2019-10-28 21:02
@JohnRoesler @Streppel hey, guys, I'll have some free time by the end of the week. I promise to have a look.

**Comment by preslavrachev** [comment] 2019-10-28 21:03
@Streppel feel free to assign it to me.

**Comment by JohnRoesler** [comment] 2019-10-29 02:25
If there is anything additional I can provide - let me know! Thanks for taking action so quickly.

**Comment by preslavrachev** [comment] 2019-11-01 17:39
I have had a brief look on the issue, in order to see, whether I can replicate it. I can. The funny thing is that the `DoSafely` function does not do anything more than set a deferred recovery, but otherwise, it should delegate straight to `Do`. As the underlying `func` I provide does not get executed at all, I am starting to believe that it has to do with some copying of value, where a pointer should have been in use.

I will keep you posted. 

---
P.S. @Streppel one Q from my side. is there a particular need to require 1.13 in the `go.mod` file? I have not upgraded yet, so I simply commented it out for my purposes. I don't think that 1.13's adoption will become mainstream so quickly.

**Comment by Streppel** [comment] 2019-11-01 17:57
@preslavrachev no specific reason indeed. Which version are you currently using?

**Comment by JohnRoesler** [comment] 2019-11-01 19:13
If I run a test just for the purpose of debugging, it generates a panic
```
func TestDoSafely(t *testing.T) {
	success := false
	Every(1).Second().DoSafely(mutatingTask, &success)

	<-Start()
}
```

```
=== RUN   TestDoSafely
panic: reflect: Call using []interface {} as type *bool

goroutine 21 [running]:
reflect.Value.call(0x133fae0, 0x13d4a70, 0x13, 0x13be056, 0x4, 0xc000144000, 0x1, 0x1, 0x5dbc7f46, 0x7ab5548, ...)
	/usr/local/Cellar/go/1.12.9/libexec/src/reflect/value.go:377 +0x1457
reflect.Value.Call(0x133fae0, 0x13d4a70, 0x13, 0xc000144000, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.12.9/libexec/src/reflect/value.go:308 +0xa4
github.com/jasonlvhit/gocron.(*Job).run(0xc0000cadc0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/john/go/src/github.com/jasonlvhit/gocron/gocron.go:129 +0x415
github.com/jasonlvhit/gocron.(*Scheduler).RunPending(0xc000118000)
	/Users/john/go/src/github.com/jasonlvhit/gocron/gocron.go:516 +0xa0
github.com/jasonlvhit/gocron.(*Scheduler).Start.func1(0xc0000cc410, 0xc000118000, 0xc00010e1c0)
	/Users/john/go/src/github.com/jasonlvhit/gocron/gocron.go:605 +0x42
created by github.com/jasonlvhit/gocron.(*Scheduler).Start
	/Users/john/go/src/github.com/jasonlvhit/gocron/gocron.go:601 +0x87

Process finished with exit code 1
```

**Comment by preslavrachev** [comment] 2019-11-01 22:29
@Streppel i have created a PR with the fix, and some minor improvements. Please, check it out and make sure to run the tests locally. Please, also keep in mind that three tests failed on my machine even when running them out of `master`: 

- `TestDaily`
- `TestWeekdayAferToday`
- `TestWeekdayAt`

Those should not have been caused by my changes. I suggest however that we open up a new issue, where we take care of fixing them, and set up some basic CI (GitHub Actions or Travis) to prevent further such cases.

**Comment by Streppel** [comment] 2019-11-02 20:11
@preslavrachev thank you! Yea, indeed the tests could use some revision... I'll take a look at this as soon as I get some time, thanks for the warning. I'll be creating the issues :)

**Closed** 2019-11-03 12:44 UTC
Labels: 2 - Working <= 5, bug
